name: delegate
version: 1.0.4
author: Samuel Hapák <samuel.hapak@vacuumapps.com>
description: Library providing support for event delegation.
homepage: https://github.com/hleumas/dart-delegate
dev_dependencies:
  unittest: any
